### ISSUE TITLE
请问 fcitx-qt5-gui-wrapper 的获取方式

### ISSUE THREAD

**Issue by hosiet** [xuzhao9/fcitx-rime-config#4]
这个工具是 fcitx5 提供的吗？在常见发行版中，应该如何安装？

**Comment by xuzhao9** [comment]
这个工具来自我对fcitx-qt5的修改：https://github.com/xuzhao9/fcitx-qt5，见guiwrapper子目录。
我已经向fcitx-qt5的开发者提交了PR，目前尚未处理完成。

**Comment by xuzhao9** [comment]
Fcitx-qt5 merged the PR. Close this issue.
